/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : CategoryId,
  'order' : bigint,
  'name' : string,
  'createdAt' : bigint,
}
export type CategoryId = string;
export interface SiteContent { 'key' : SiteContentKey, 'value' : string }
export type SiteContentKey = string;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : VideoId,
  'categoryId' : CategoryId,
  'title' : string,
  'featured' : boolean,
  'order' : bigint,
  'thumbnailBlobId' : [] | [string],
  'createdAt' : bigint,
  'description' : string,
  'blobId' : [] | [string],
  'isYoutube' : boolean,
  'youtubeUrl' : [] | [string],
}
export type VideoId = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  /**
   * / Authorization
   */
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Category CRUD (Admin-only Write)
   */
  'createCategory' : ActorMethod<[string, string, bigint], undefined>,
  /**
   * / Video CRUD (Admin-only Write)
   */
  'createVideo' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      boolean,
      [] | [string],
      [] | [string],
      [] | [string],
      boolean,
      bigint,
    ],
    undefined
  >,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllSiteContent' : ActorMethod<[], Array<SiteContent>>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  /**
   * / User Profile Management
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategory' : ActorMethod<[string], [] | [Category]>,
  'getSiteContent' : ActorMethod<[string], [] | [SiteContent]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideo' : ActorMethod<[string], [] | [Video]>,
  'getVideosByCategory' : ActorMethod<[string], Array<Video>>,
  /**
   * / Init with Default Data
   */
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Site Content CRUD (Admin-only Write)
   */
  'setSiteContent' : ActorMethod<[string, string], undefined>,
  'updateCategory' : ActorMethod<[string, string, bigint], undefined>,
  'updateVideo' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      boolean,
      [] | [string],
      [] | [string],
      [] | [string],
      boolean,
      bigint,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];